### ISSUE TITLE
ELCAN Scope on GRY SBR

### ISSUE THREAD

**Issue by Mathematical-Jin** [civilgamers/bug-reports#254] opened 2019-06-22 16:04 UTC
**Hello Developers,**
I was in an Admin Sit and this guy was complaining about a broken sight called ELCAN. They said that everything inside the sight was functioning however when he's ADS, everything outside the sight is permanently stuck on one frame.

**Kind Regards**

**Jin**

**Comment by Cerbiac** [comment] 2019-10-13 05:28
Duplicate of #248

**Closed by Cerbiac** 2019-10-13 05:28 UTC
Labels: Bug, DarkRP, Labeled
