### ISSUE TITLE
Reduce pickaxe mining volume

### ISSUE THREAD

**Issue by anthonysharpy** [civilgamers/bug-reports#581] opened 2019-10-02 22:57 UTC
**Related Problem** 

It's too loud. You have to turn your volume down and that means you can't hear people when they speak through their mics at you. Also it's like a needle being scraped against your ear drum.

**Preferred Solution** 

Reduce the volume a tad.

**Comment by HydroCG** [comment] 2020-04-05 03:25
work in progress, duplicate of item work item (not a bug) not listed in this repo

**Closed by HydroCG** 2020-04-05 03:25 UTC
Labels: DarkRP, Labeled, Suggestion
