### ISSUE TITLE
Wifi hacking bug

### ISSUE THREAD

**Issue by DukeR009** [civilgamers/bug-reports#542] opened 2019-09-23 13:10 UTC
![Wifi bug](https://user-images.githubusercontent.com/55699271/65428182-3ddb3880-de14-11e9-96c6-b9d588976692.JPG)
plz fix ;)

**Comment by Cerbiac** [comment] 2019-09-23 19:44
Duplicate of #65

**Closed** 2019-09-27 01:14 UTC
Labels: accepted, bug, cityrp, darkrp, duplicate
