### ISSUE TITLE
Visual glitch

### ISSUE THREAD

**Issue by AllahSoundlezz** [civilgamers/bug-reports#468] opened 2019-08-23 16:31 UTC
https://imgur.com/a/D1Q38oJ
Visual glitch , when i disguise sometimes i see my cosmetics from thief

**Comment by Cerbiac** [comment] 2019-08-23 20:14
Duplicate of #430

**Comment by Cerbiac** [comment] 2019-08-23 20:16
Duplicate of #402

**Closed** 2019-09-27 01:05 UTC
Labels: accepted, bug, darkrp, duplicate
